# Enlaces de video para DJ GER
video.1.title=Set Live en Club Sunset
video.1.url=https://www.youtube.com/watch?v=5qap5aO4i9A
video.2.title=Trailer del nuevo show
video.2.url=https://www.youtube.com/watch?v=3JZ4pnNtyxQ
video.3.title=Prueba Local
video.3.url=static/video_prueba.mp4
