# Enlaces de video para DJ GER
video.1.title=Ritmo Nocturno en Club Sunset
video.1.url=https://youtu.be/QnCABE3E1Ng?is=fLOphrC6puDHNzN_
video.2.title=Odisea Electro: Nuevo Show
video.2.url=https://youtu.be/b1P4IXA41Xs?is=VztSPdBPF44ehluY
video.3.title=Beat Takeover: Prueba Local
video.3.url=https://youtu.be/fjmdXSNByh4?is=s3SSRvBg6hRkaKLx
